"""empty message

Revision ID: 1a936c1b6714
Revises: 
Create Date: 2022-10-27 22:07:38.102032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a936c1b6714'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('idevent', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=45), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('max_visitors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idevent')
    )
    op.create_table('user',
    sa.Column('iduser', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=45), nullable=False),
    sa.Column('city', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('role', sa.Enum('User', 'Admin'), nullable=False),
    sa.PrimaryKeyConstraint('iduser')
    )
    op.create_table('ticket',
    sa.Column('idticket', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('is_bought', sa.Boolean(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('iduser', sa.Integer(), nullable=True),
    sa.Column('idevent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idevent'], ['event.idevent'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['iduser'], ['user.iduser'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idticket')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('user')
    op.drop_table('event')
    # ### end Alembic commands ###
